### ISSUE TITLE
改行コードの統一

### ISSUE THREAD

**Issue by kou029w** [videomark/videomark#164]
いくつか改行コードがCR/LFなファイルが混在していて気になった。かなり古いWindowsのバージョンを使っている人以外のことを考えると基本的にLFに統一しておくほうが望ましいと考える。下記のファイルの改行コードが変更されてコードベースに反映されればクローズ。

videomark/videomark

```console
$ git grep --cached -l -I $'\r$'
packages/sodium/NOTICE
packages/videomark-extension/NOTICE
packages/videomark-log-view/NOTICE
```

**Comment by kyoshino** [comment]
今後も Windows ユーザーが参加すると混在する可能性があるので、設定ファイルで指定しておいた方が良いと思います。

`.gitattributes` ファイル

```
* text=auto eol=lf
```

`.editorconfig` ファイル

```
root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
```
