### ISSUE TITLE
エディタの設定ファイルの配置

### ISSUE THREAD

**Issue by kou029w** [videomark/videomark#170]
今後も Windows ユーザーが参加すると混在する可能性があるので、設定ファイルで指定しておいた方が良いと思います。

`.gitattributes` ファイル

```
* text=auto eol=lf
```

`.editorconfig` ファイル

```
root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
```

_Originally posted by @kyoshino in https://github.com/videomark/videomark/issues/164#issuecomment-1225203314_

**Comment by kyoshino** [comment]
いずれも #198 に含めました。

**Comment by kyoshino** [comment]
これも #198 に含める必要はないですね。

**Comment by kyoshino** [comment]
そういえば VideoMark とは関係ないですが、別のプロジェクトで日本語名のファイルが投入されて Mac 特有の濁点分離問題が起きたことがあります。念のため対処したいが、どうもその設定は各人の `.gitconfig` に入れるものであって、プロジェクトごとの `.gitattributes` では解決できないようですね。なかなか面倒。

- [Mac上のgitで日本語を含むファイルが何故かUntrackedになる場合](https://qiita.com/FrozenVoice/items/c18b4b9db8d5e7720b1e)
- [Is it safe to set git's core.precomposeunicode = true globally?](https://stackoverflow.com/questions/15231589/is-it-safe-to-set-gits-core-precomposeunicode-true-globally)
